import {  Poppins } from "next/font/google";
import "./globals.css";




const poppins=Poppins({
  variable:'--poppins-font',
  subsets:['latin'],
  weight:['400','500','600','700','800','900']
})



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className={`min-h-full ${poppins.className}` }>{children}</body>
    </html>
  );
}
